const expressJ = require('express');
const { driverAuth: dAuth2 } = require('../middleware/auth');
const jobsCtrl = require('../controllers/jobs');
const jobsRouter = expressJ.Router();
jobsRouter.get('/', dAuth2, jobsCtrl.listDriverJobs);
jobsRouter.get('/:id', dAuth2, jobsCtrl.getJob);
jobsRouter.post('/:id/accept', dAuth2, jobsCtrl.acceptAvailableJob);
jobsRouter.get('/:id/tracking', dAuth2, jobsCtrl.tracking);
jobsRouter.post('/:id/pickup-confirm', dAuth2, jobsCtrl.pickupConfirm);
jobsRouter.post('/:id/delivery-confirm', dAuth2, jobsCtrl.deliveryConfirm);
module.exports = jobsRouter;