### Auth

### Driver Auth
### POST /api/auth/driver/start → { request_id }
POST http://localhost:3459/api/auth/driver/start
Content-Type: application/json

{
  "phoneNumber": "+256700000010"
}

### POST /api/auth/driver/verify → { token, role: 'driver', user }
##### token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjZhMWM3MDZlNDFhNzljODUwMTQiLCJyb2xlIjoiZHJpdmVyIiwic3ViTW9kZWwiOiJEcml2ZXIiLCJpYXQiOjE3NTc1NTUyMTUsImV4cCI6MTc2MDE0NzIxNX0.ZVwnMMSdESaSr0J_H615zeQabczh5VJONMN22zp511Y
POST http://localhost:3459/api/auth/driver/verify
Content-Type: application/json

{
  "request_id": "68c229ef1af62fa537335ea9",
   "code": "589254"
}

### Farmer Auth
### POST /api/auth/{driver|farmer|buyer}/login → { token, role, user }
###### token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYxZGQ0ZjYzOTczNTYzZWMxNGMiLCJyb2xlIjoiZmFybWVyIiwic3ViTW9kZWwiOiJVc2VyIiwiaWF0IjoxNzU3NTU0ODQ5LCJleHAiOjE3NjAxNDY4NDl9.uzFsFzhMyC58LkS0KTG8bkEFuAvE-lKHl5k1PZeUc3Y
POST http://localhost:3459/api/auth/farmer/login
Content-Type: application/json

{
  "email": "farmer001@fty.com",
  "password": "farmer123"
}


### Buyer Auth
### email:buyer001@fty.com password: buyer123
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYyYWQ0ZjYzOTczNTYzZWMxNjIiLCJyb2xlIjoiYnV5ZXIiLCJzdWJNb2RlbCI6IlVzZXIiLCJpYXQiOjE3NTc1NTQ2MTcsImV4cCI6MTc2MDE0NjYxN30.sLXxeBw-LHrT5cKNRt50FH3U-wwBfwKMwfgnqMZB6KA
POST http://localhost:3459/api/auth/buyer/login
Content-Type: application/json

{
  "email": "buyer001@buyers.fty.com",
  "password": "buyer123"
}

###

### Admin Auth


### Password Reset
######## POST /api/auth/password/reset → { message }
######## POST /api/auth/password/forgot → { message }

### Farmer Routes
##### Farmer create lot
#### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYyYWQ0ZjYzOTczNTYzZWMxNjIiLCJyb2xlIjoiYnV5ZXIiLCJzdWJNb2RlbCI6IlVzZXIiLCJpYXQiOjE3NTc1NTQ2MTcsImV4cCI6MTc2MDE0NjYxN30.sLXxeBw-LHrT5cKNRt50FH3U-wwBfwKMwfgnqMZB6KA
### POST /api/products/lots

POST http://localhost:3459/api/products/lots
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYxZGQ0ZjYzOTczNTYzZWMxNGMiLCJyb2xlIjoiZmFybWVyIiwic3ViTW9kZWwiOiJVc2VyIiwiaWF0IjoxNzU3NTU0ODQ5LCJleHAiOjE3NjAxNDY4NDl9.uzFsFzhMyC58LkS0KTG8bkEFuAvE-lKHl5k1PZeUc3Y

{
  "produceType": "Coffee",
  "description": "Robusta.",
  "quantity": 349,
  "reservePrice": 18000,
  "unit": "Kg",
  "pickup": {
    "name": "Berna's Farm",
    "address": "123 West Lake, Countryside",
    "lat": 34.0522,
    "lng": -118.2437
  }
}

##### Farmer get lots

##### GET /api/products/lots

GET http://localhost:3459/api/products/lots/open
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYxZGQ0ZjYzOTczNTYzZWMxNGMiLCJyb2xlIjoiZmFybWVyIiwic3ViTW9kZWwiOiJVc2VyIiwiaWF0IjoxNzU3NTU0ODQ5LCJleHAiOjE3NjAxNDY4NDl9.uzFsFzhMyC58LkS0KTG8bkEFuAvE-lKHl5k1PZeUc3Y


##### GET /api/products/lots?status=open

##### Farmer get lot by id
##### Farmer update lot
##### Farmer delete lot

##### Buyer bids on lot
#### POST /api/products/lots/{lotId}/bids
##### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYyYWQ0ZjYzOTczNTYzZWMxNjIiLCJyb2xlIjoiYnV5ZXIiLCJzdWJNb2RlbCI6IlVzZXIiLCJpYXQiOjE3NTc1NTQ2MTcsImV4cCI6MTc2MDE0NjYxN30.sLXxeBw-LHrT5cKNRt50FH3U-wwBfwKMwfgnqMZB6KA
##### bid id 68bf83a1705cd645f082a386
POST http://localhost:3459/api/products/lots/68c2283c1af62fa537335e8a/bids
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYyYWQ0ZjYzOTczNTYzZWMxNjIiLCJyb2xlIjoiYnV5ZXIiLCJzdWJNb2RlbCI6IlVzZXIiLCJpYXQiOjE3NTc1NTQ2MTcsImV4cCI6MTc2MDE0NjYxN30.sLXxeBw-LHrT5cKNRt50FH3U-wwBfwKMwfgnqMZB6KA
Content-Type: application/json

{
  "amount": 360000,
  "note": "Looking forward to these local Eggs!",
  "quantity": 340,
  "units":"Trays"
}

##### Farmer gets bids on lot
##### GET /api/products/lots/{lotId}/bids
GET http://localhost:3459/api/products/lots/68c2283c1af62fa537335e8a/bids
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYxZGQ0ZjYzOTczNTYzZWMxNGMiLCJyb2xlIjoiZmFybWVyIiwic3ViTW9kZWwiOiJVc2VyIiwiaWF0IjoxNzU3NTU0ODQ5LCJleHAiOjE3NjAxNDY4NDl9.uzFsFzhMyC58LkS0KTG8bkEFuAvE-lKHl5k1PZeUc3Y

##### Farmer accepts bid on lot
##### POST /api/products/lots/{lotId}/bids/{bidId}/accept
POST http://localhost:3459/api/products/lots/68c2283c1af62fa537335e8a/bids/68c229641af62fa537335e97/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYxZGQ0ZjYzOTczNTYzZWMxNGMiLCJyb2xlIjoiZmFybWVyIiwic3ViTW9kZWwiOiJVc2VyIiwiaWF0IjoxNzU3NTU0ODQ5LCJleHAiOjE3NjAxNDY4NDl9.uzFsFzhMyC58LkS0KTG8bkEFuAvE-lKHl5k1PZeUc3Y

##### (PaymentIntent type=product, status=authorized)
##### Farmer rejects bid on lot
##### Farmer gets all accepted bids
##### Farmer gets all rejected bids
##### Farmer gets all bids

#### Buyer payments for accepted bids
#####  create Delivery Request prefilled with pickup location (farmer address) and dropoff location (buyer address)


### Buyer -> Driver (Delivery) Bidding
#### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjZhMWM3MDZlNDFhNzljODUwMTQiLCJyb2xlIjoiZHJpdmVyIiwic3ViTW9kZWwiOiJEcml2ZXIiLCJpYXQiOjE3NTc1NTUyMTUsImV4cCI6MTc2MDE0NzIxNX0.ZVwnMMSdESaSr0J_H615zeQabczh5VJONMN22zp511Y
##### Driver gets all delivery requests
##### GET /api/driver/requests/open?nearLat=&nearLng=&within_km=50
GET http://localhost:3459/api/driver/requests/open?nearLat=&nearLng=&within_km=50
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjZhMWM3MDZlNDFhNzljODUwMTQiLCJyb2xlIjoiZHJpdmVyIiwic3ViTW9kZWwiOiJEcml2ZXIiLCJpYXQiOjE3NTc1NTUyMTUsImV4cCI6MTc2MDE0NzIxNX0.ZVwnMMSdESaSr0J_H615zeQabczh5VJONMN22zp511Y

##### Driver places bid (quoute) on delivery request
##### POST /api/driver/requests/{id}/quote
POST http://localhost:3459/api/driver/requests/68c229c91af62fa537335ea6/quote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjZhMWM3MDZlNDFhNzljODUwMTQiLCJyb2xlIjoiZHJpdmVyIiwic3ViTW9kZWwiOiJEcml2ZXIiLCJpYXQiOjE3NTc1NTUyMTUsImV4cCI6MTc2MDE0NzIxNX0.ZVwnMMSdESaSr0J_H615zeQabczh5VJONMN22zp511Y

{
  "amount":25000,
  "etaMinutes": 20,
  "note":"I can transport Coffee"
}

##### Buyer gets all bids on delivery request
##### Buyer accepts bid on delivery request
##### POST /api/buyer/requests/{id}/quotes/{quoteId}/accept
##### Creates DriverJob with codes (farmerCode, buyerCode) and status=awaiting_driver_confirm.
POST http://localhost:3459/api/buyer/requests/68c229c91af62fa537335ea6/quotes/68c22a781af62fa537335eb4/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjYyYWQ0ZjYzOTczNTYzZWMxNjIiLCJyb2xlIjoiYnV5ZXIiLCJzdWJNb2RlbCI6IlVzZXIiLCJpYXQiOjE3NTc1NTQ2MTcsImV4cCI6MTc2MDE0NjYxN30.sLXxeBw-LHrT5cKNRt50FH3U-wwBfwKMwfgnqMZB6KA

##### PaymentIntent type=transport, status=authorized
##### Buyer rejects bid on delivery request
##### Buyer authorizes payment for delivery (escrow)
##### Driver confirms the bid and starts delivery (job)-> active
##### POST /api/driver/requests/quotes/{quoteId}/confirm → job active
POST http://localhost:3459/api/driver/requests/quotes/68c22a781af62fa537335eb4/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjZhMWM3MDZlNDFhNzljODUwMTQiLCJyb2xlIjoiZHJpdmVyIiwic3ViTW9kZWwiOiJEcml2ZXIiLCJpYXQiOjE3NTc1NTUyMTUsImV4cCI6MTc2MDE0NzIxNX0.ZVwnMMSdESaSr0J_H615zeQabczh5VJONMN22zp511Y


####### 


### Pickup -> Deliver (Escrow) Releases
##### Pickup at farmer location -> Driver confirms pickup (Enters farmer code)-> Escrow payment for delivery is released to driver
##### POST /api/driver/jobs/{jobId}/pickup-confirm
POST http://localhost:3459/api/driver/jobs/68c22a911af62fa537335ebc/pickup-confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjZhMWM3MDZlNDFhNzljODUwMTQiLCJyb2xlIjoiZHJpdmVyIiwic3ViTW9kZWwiOiJEcml2ZXIiLCJpYXQiOjE3NTc1NTUyMTUsImV4cCI6MTc2MDE0NzIxNX0.ZVwnMMSdESaSr0J_H615zeQabczh5VJONMN22zp511Y

{
  "code": "5293"
}

######## Driver confirms delivery (Enters buyer code) -> Escrow payment for delivery is released to driver
##### POST /api/driver/jobs/{jobId}/delivery-confirm
POST http://localhost:3459/api/driver/jobs/68c22a911af62fa537335ebc/delivery-confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGMyMjZhMWM3MDZlNDFhNzljODUwMTQiLCJyb2xlIjoiZHJpdmVyIiwic3ViTW9kZWwiOiJEcml2ZXIiLCJpYXQiOjE3NTc1NTUyMTUsImV4cCI6MTc2MDE0NzIxNX0.ZVwnMMSdESaSr0J_H615zeQabczh5VJONMN22zp511Y

{
  "code": "5672"
}

##### Delivery at buyer location -> Buyer confirms delivery (Enters driver code) -> Escrow payment for lot is released to farmer
### POST /api/payments/jobs/{jobId}/release-nfc